name = input("Enter Your Name = ")
branch = input("Enter Your Branch = ")
gender = input("Enter Your Gender = ")
clg = input("Enter Your College = ")
age = input("Enter Your Age = ")
print("Name = ",name)
print("Branch = ",branch)
print("Gender = ",gender)
print("College = ",clg)
print("Age = ",age)
